run:
  timeout: 8m
issues:
  exclude-dirs:
    - data
linters:
  disable-all: true
  enable:
    # default
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    # style
    - gofmt
    - stylecheck
    - whitespace
