name: CI Go
on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - .github/workflows/go.yml
      - '**.go'
      - go.*
      - Makefile
run-name: CI Go ${{ github.sha }} by @${{ github.actor }}
jobs:
  build:
    runs-on: ubuntu-latest
    container: golang:1.20.4
    steps:
      - name: setup
        run: |
          git config --global --add safe.directory $(pwd)
      - uses: actions/checkout@v3
      - name: build
        run: make build
      - name: tidy
        run: |
          go mod tidy
          git diff --exit-code
      - name: test
        run: make unit
  lint:
    runs-on: ubuntu-latest
    container: golangci/golangci-lint:v1.52.2
    steps:
      - uses: actions/checkout@v3
      - name: Lint
        run: golangci-lint run ./...
