name: Python CI
on:
  pull_request:
    paths:
      - localstack/**
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: psf/black@stable
        with:
          options: "--check --verbose"
          version: "22.6.0"
